// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAatSWcNKC3W5d5qRy5VHAdo_G0PuUkj88',
    appId: '1:225348958001:web:49cfc27501d6a6cd8e2210',
    messagingSenderId: '225348958001',
    projectId: 'backcaps-logistics',
    authDomain: 'backcaps-logistics.firebaseapp.com',
    storageBucket: 'backcaps-logistics.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq5baR5kXXXaWZkI5Fx_wrnMfL_emj3Jk',
    appId: '1:225348958001:android:080d5e6e962bea718e2210',
    messagingSenderId: '225348958001',
    projectId: 'backcaps-logistics',
    storageBucket: 'backcaps-logistics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG06DAMbrTBMSqrc59cfkDu_pyGAJhbEg',
    appId: '1:225348958001:ios:3214ce8afd4c181c8e2210',
    messagingSenderId: '225348958001',
    projectId: 'backcaps-logistics',
    storageBucket: 'backcaps-logistics.appspot.com',
    iosBundleId: 'com.backcaps.backcapsLogistics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG06DAMbrTBMSqrc59cfkDu_pyGAJhbEg',
    appId: '1:225348958001:ios:7fd0e047246925e08e2210',
    messagingSenderId: '225348958001',
    projectId: 'backcaps-logistics',
    storageBucket: 'backcaps-logistics.appspot.com',
    iosBundleId: 'com.backcaps.backcapsLogistics.RunnerTests',
  );
}
